### ISSUE TITLE
swagger ui 3.x

### ISSUE THREAD

**Issue by willin** [zaaack/koa-joi-swagger#1]
when to update to swagger ui 3.x version?

**Comment by zaaack** [comment]
I have tried before, but I can't find a way to adding crsf header in swagger ui 3.x,  and  the benefit of upgrading isn't attractive enough for me. Don't know whether having any updates. I'll find a way to make v3 optional these days. When v3.x is more stable I would upgrade.

**Comment by zaaack** [comment]
@willin Updated!
