### ISSUE TITLE
如何使用v3

### ISSUE THREAD

**Issue by huowenxuan** [zaaack/koa-joi-swagger#4]
![image](https://user-images.githubusercontent.com/13825444/44895843-b9110e80-ad28-11e8-9b5e-048011442ae5.png)

```
const mixedDoc = {
  swagger: "2.0",
}

const mixedDoc = {
  openapi: 3.0,
}

const mixedDoc = {
  openapi: "3.0",
}
```
都不管用

**Comment by zaaack** [comment]
![image](https://user-images.githubusercontent.com/5233940/44895902-e5c52600-ad28-11e8-952d-f2a2dae27734.png)

**Comment by huowenxuan** [comment]
设置过 v3: true，并且yarn add swagger-ui-dist

**Comment by zaaack** [comment]
@huowenxuan 请参考测试目录下的， https://github.com/zaaack/koa-joi-swagger/blob/master/test/fixtures/mixed-doc.js#L7

我这边测试是可以的

**Comment by zaaack** [comment]
`V3=1 SERVE=1 npx babel-node ./test/fixtures/server.js`

**Comment by huowenxuan** [comment]
嗯谢谢，把下面的代码去掉就好了，其他不需要变

```
const swaggerDoc = toSwaggerDoc(mixedDoc);
fs.writeFileSync('./swagger/swagger-doc-from-mixed-doc.json', JSON.stringify(swaggerDoc, null, 2));
```
